{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend.fullname" . }}
  labels: {{- include "backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels: {{- include "backend.selectorLabels" . | nindent 6 }}
{{- end }}
