sonar.projectKey=cloudforge-api
sonar.projectName=CloudForge API
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.sourceEncoding=UTF-8
