#!/usr/bin/env bash
# Render the Helm charts into plain Kubernetes manifests under k8s-manifests/rendered/<env>/.
# Helm charts are the single source of truth; the rendered tree serves
#   - reviewers who want to read plain YAML in PRs,
#   - `kubectl apply -k k8s-manifests/rendered/<env>` for clusters without Helm/Argo CD,
#   - static policy/schema checks in CI (kubeconform, trivy config).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HELM="${HELM:-helm}"
declare -A NS=(
  [platform]=istio-system [postgres]=database [redis]=database
  [backend]=backend [apache-proxy]=backend [frontend]=frontend
)
ORDER=(platform postgres redis backend apache-proxy frontend)

for env in local eks; do
  out="$ROOT/k8s-manifests/rendered/$env"
  rm -rf "$out" && mkdir -p "$out"
  resources=()
  for chart in "${ORDER[@]}"; do
    file="$out/$(printf '%02d' ${#resources[@]})-$chart.yaml"
    {
      echo "# GENERATED by scripts/render-manifests.sh from helm-charts/charts/$chart"
      echo "# with gitops/environments/$env/$chart.yaml. Do not edit by hand."
      "$HELM" template "$chart" "$ROOT/helm-charts/charts/$chart" \
        --namespace "${NS[$chart]}" \
        -f "$ROOT/gitops/environments/$env/$chart.yaml" \
        --skip-tests
    } > "$file"
    resources+=("$(basename "$file")")
  done
  {
    echo "# GENERATED by scripts/render-manifests.sh"
    echo "apiVersion: kustomize.config.k8s.io/v1beta1"
    echo "kind: Kustomization"
    echo "resources:"
    for r in "${resources[@]}"; do echo "  - $r"; done
  } > "$out/kustomization.yaml"
  echo "rendered $env -> k8s-manifests/rendered/$env (${#resources[@]} files)"
done
